name: mathhelperr

services:
  webapi:
    build:
      context: .
      dockerfile: .dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MathHelperDocker;User Id=sa;Password=Macko1234;Encrypt=false
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Macko1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
