# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #get code
    - uses: actions/checkout@v4
    # .net install
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
   
    # dependencys install
    - name: Restore dependencies
      #working-directory: Backend/MathHelper/MathHelperr
      run: dotnet restore Backend/MathHelper/MathHelperr/MathHelperr.csproj
   
    # build
    - name: Build
     # run: dotnet build --no-restore
      run: dotnet build Backend/MathHelper/MathHelperr/MathHelperr.csproj --no-restore --configuration Release

    # Unit tesztek futtat치sa
    - name: Run Unit Tests
      run: dotnet test Backend/MathHelper/UnitTest/UnitTest.csproj --verbosity normal

    # Integr치ci칩s tesztek futtat치sa
    - name: Run Integration Tests
      run: dotnet test Backend/MathHelper/IntegrationTest/IntegrationTest.csproj --verbosity normal
